export const palavrasChaveConversa: Set<string> = new Set([
  "variavel", "variáveis", "variavél", "variaveis",
  "estrutura", "estruturas",
  "lista", "listas", "lissta", "lsta",
  "condicional", "condicionais", "condição", "condicoes",
  "verificação", "verificações", "verificacao", "verificacoes",
  "função", "funcoes", "funçao", "funçoes",
  "laço", "laços", "loop", "loops", "repetição", "repeticoes",
  "inteiro", "int", "numero", "número", "numeros", "números",
  "decimal", "float", "double",
  "booleano", "boolean", "bool",
  "verdadeiro", "falso", "true", "false",
  "soma", "subtração", "multiplicação", "divisão",
  "aritmética", "aritmetica",
  "expressão", "expressao", "expresao", "expressões",
  "atribuição", "atribuicao", "igualdade", "igual",
  "if", "else", "elif", "switch", "case",
  "array", "vetor", "matriz", "conjunto", "dicionário",
  "chave", "valor", "objeto", "classe",
  "função recursiva", "recursão", "recursao",
  "algoritmo", "algoritmos",
  "programa", "programação", "logica", "lógica",
  "variable", "variables", "list", "lists",
  "conditional", "conditionals", "condition",
  "if", "else", "elif", "switch", "case",
  "loop", "loops", "while", "for",
  "function", "functions", "method", "methods",
  "integer", "float", "double", "number", "numbers",
  "boolean", "true", "false",
  "expression", "assignment", "operator", "operators",
  "array", "matrix", "object", "class", "dictionary",
  "algorithm", "program", "programming", "logic",
  "varivel", "verificaçao", "verifica", "strutura",
  "condisonal", "condiçao", "funçaõ", "recursivo"
]);
